/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { MemberInfoDto } from './memberInfoDto';

export interface ApplicationListResponseDto {
  canceled?: boolean;
  partnerInfoDto?: MemberInfoDto;
  status?: string;
  writerInfoDto?: MemberInfoDto;
}
