/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */

export interface ApplicationCreateResponseDto {
  canceled?: boolean;
  id?: number;
  partnerId?: string;
  partnerIdAsLong?: number;
  status?: string;
  writerId?: string;
  writerIdAsLong?: number;
}
