/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { ChatRoom } from './chatRoom';

export interface ChatMessage {
  chatRoom?: ChatRoom;
  content?: string;
  createDate?: string;
  id?: number;
  senderId?: number;
  writerName?: string;
}
