/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { ChatMessage } from './chatMessage';

export interface ChatMessagesDto {
  hasNext?: boolean;
  messages?: ChatMessage[];
}
