/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationListDto } from './applicationListDto';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface PageApplicationListDto {
  content?: ApplicationListDto[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject[];
  totalElements?: number;
  totalPages?: number;
}
