/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileGender } from './profileGender';
import type { Member } from './member';

export interface Profile {
  age?: number;
  benchPress?: number;
  createDate?: string;
  deadLift?: number;
  gender?: ProfileGender;
  id?: number;
  member?: Member;
  modifyDate?: string;
  squat?: number;
  totalWeight?: number;
}
