/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */

export type ProfileGender = typeof ProfileGender[keyof typeof ProfileGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileGender = {
  Female: 'Female',
  Male: 'Male',
} as const;
