/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { MemberInfoDto } from './memberInfoDto';
import type { ProfileDto } from './profileDto';
import type { RecruitmentDto } from './recruitmentDto';

export interface RecruitmentListDetailResponseDto {
  memberInfoDto?: MemberInfoDto;
  profileDto?: ProfileDto;
  recruitmentDto?: RecruitmentDto;
}
