/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { Member } from './member';

export interface RecruitmentListResponseDto {
  member?: Member;
  partnerAge?: number;
  partnerGender?: string;
  recruit_date?: string;
  routine?: string;
  title?: string;
}
