/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */
import type { LocalTime } from './localTime';
import type { Member } from './member';

export interface RecruitmentListDetailResponseDto {
  content?: string;
  duration?: LocalTime;
  id?: number;
  member?: Member;
  partnerAge?: number;
  partnerGender?: string;
  place?: string;
  recruit_date?: string;
  routine?: string;
  title?: string;
}
