/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */

export interface SignUpDto {
  checkPassword?: string;
  imgUrl?: string;
  name?: string;
  nickname?: string;
  password: string;
  roles?: string[];
  username: string;
}
