/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * COMMERCE
 * COMMERCE REST API DOC
 * OpenAPI spec version: 1.0.0
 */

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}
